# Generated by Django 4.2.3 on 2023-07-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0002_iha_rentrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentrecord',
            name='rental_end_date',
        ),
        migrations.RemoveField(
            model_name='rentrecord',
            name='rental_start_date',
        ),
        migrations.AddField(
            model_name='iha',
            name='rental_end_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iha',
            name='rental_start_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
