# Generated by Django 4.2.3 on 2023-07-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0003_remove_rentrecord_rental_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iha',
            name='rental_end_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='iha',
            name='rental_start_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
